### ISSUE TITLE
Remove dependency of jquery-rails

### ISSUE THREAD

**Issue by dempfi** [davydotcom/retina_tag#17]
There is no need of gem `jquery-rails` in deps because jquery is possible to connect to project in many ways like from bower, webpack from cdn and etc. And as I understand `jquery-rails` in deps is only for being sure that user will have jquery. 

What do you think @davydotcom? can you remove this dep and add some note in readme that jquer is necessary to be in project?

**Comment by davydotcom** [comment]
fixed in 1.4.1
